import login from './Login';
import register from './Register';
import changeMail from './ChangeMail';
import changePassword from './ChangePassword';
import dashboard from './Dashboard';
import videoPlayer from './VideoPlayer';
import launch from './Launch';
import leftMenu from './LeftMenu';
import howToHunt from './HowToHunt';
import originals from './Originals';
import updateCard from './UpdateCard';
import feedback from './Feedback';
import termOfUse from './TermOfUse';
import faq from './FAQ';
import customerService from './CustomerService';
import account from './Account';
import huntDetail from './HuntDetail';
import home from './Home';
import forgotPassword from './ForgotPassword';
import changePlan from './ChangePlan';

export const Login = login;
export const Register = register;
export const ChangeMail = changeMail;
export const ChangePassword = changePassword;
export const Dashboard = dashboard;
export const VideoPlayer = videoPlayer;
export const Launch = launch;
export const LeftMenu = leftMenu;
export const HowToHunt = howToHunt;
export const Originals = originals;
export const UpdateCard = updateCard;
export const Feedback = feedback;
export const TermOfUse = termOfUse;
export const FAQ = faq;
export const CustomerService = customerService;
export const Account = account;
export const HuntDetail = huntDetail;
export const Home = home;
export const ForgotPassword = forgotPassword;
export const ChangePlan = changePlan;
