import {StyleSheet} from 'react-native';
import {Constants, Colors, Styles} from "@common"

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  form: {
    ...Styles.matchParent,
    marginHorizontal:35,
    marginTop:20
  },
  input:{
    marginBottom:8,
  },
  logo:{
  	width:200,
  	height:60,
  	resizeMode:'contain',
  	alignSelf:'center',
  	marginTop:50
  },
  labelBill:{
    fontSize:Constants.FontSize.medium,
    color:'white',
    marginBottom:5
  },
  row:{
    width:'100%',
    flexDirection:'row',
    alignItems:'center'
  },
  code:{
    flex:1,
    marginRight:5
  },
  dropdown:{
    height:40,
    width:100,
    borderRadius:4,
    backgroundColor:'rgba(170,170,170,1.0)',
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    paddingHorizontal:5
  },
  dropdownText:{
    color:Colors.gray,
    fontSize:Constants.FontSize.tiny
  },
  dropdownIcon:{
    width:8,
    height:15,
    resizeMode:'contain'
  },
  month:{
    width:80,
    marginRight:5
  },
  year:{
    width:70,
  },
  btnTerm:{
    alignSelf:'center',
    marginBottom:10
  },
  btnTermText:{
    marginVertical:5,
    color:'rgba(170,170,170,1.0)',
    fontSize:12,
    textAlign:'center'
  },
  radioWrap:{
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    marginTop:10,
    marginBottom:10,
    flexWrap:'wrap'
  },
  radioButton:{
    marginTop:10,
    flexDirection:'row',
    alignItems:'flex-start'
  },
  radioText:{
    color:'white',
    fontSize:Constants.FontSize.tiny
  },
  radioSubText:{
    color:'white',
    fontSize:Constants.FontSize.superTiny
  },
  radioIcon:{
    marginRight:10,
    width:15,
    height:15,
    resizeMode:'contain'
  },
  promo:{
    flex:1,
    marginRight:5,
  },
  note:{
    width:150,
    color:'white',
    marginRight:5,
    fontSize:Constants.FontSize.tiny
  },
});
