export const SHOW_PROGRESS = "SHOW_PROGRESS"
export const HIDE_PROGRESS = "HIDE_PROGRESS"

export const LOGIN_PENDING = "LOGIN_PENDING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const GET_SHOWS_PENDING = "GET_SHOWS_PENDING"
export const GET_SHOWS_SUCCESS = "GET_SHOWS_SUCCESS"
export const GET_SHOWS_FAILURE = "GET_SHOWS_FAILURE"

export const GET_SERIES_SHOW_PENDING = "GET_SERIES_SHOW_PENDING"
export const GET_SERIES_SHOW_SUCCESS = "GET_SERIES_SHOW_SUCCESS"
export const GET_SERIES_SHOW_FAILURE = "GET_SERIES_SHOW_FAILURE"

export const SELECTED_EPISODE = "SELECTED_EPISODE"
export const SELECTED_EPISODE_INDEX = "SELECTED_EPISODE_INDEX"

export const GET_ASSET_PENDING = "GET_ASSET_PENDING"
export const GET_ASSET_SUCCESS = "GET_ASSET_SUCCESS"
export const GET_ASSET_FAILURE = "GET_ASSET_FAILURE"

export const REGISTER_SUBSCRIBE_PENDING = "REGISTER_SUBSCRIBE_PENDING"
export const REGISTER_SUBSCRIBE_SUCCESS = "REGISTER_SUBSCRIBE_SUCCESS"
export const REGISTER_SUBSCRIBE_FAILURE = "REGISTER_SUBSCRIBE_FAILURE"

export const GET_PLANS_PENDING = "GET_PLANS_PENDING"
export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS"
export const GET_PLANS_FAILURE = "GET_PLANS_FAILURE"

export const GET_CUSTOMER_SERVICE_PENDING = "GET_CUSTOMER_SERVICE_PENDING"
export const GET_CUSTOMER_SERVICE_SUCCESS = "GET_CUSTOMER_SERVICE_SUCCESS"
export const GET_CUSTOMER_SERVICE_FAILURE = "GET_CUSTOMER_SERVICE_FAILURE"

export const GET_TERM_SERVICE_PENDING = "GET_TERM_SERVICE_PENDING"
export const GET_TERM_SERVICE_SUCCESS = "GET_TERM_SERVICE_SUCCESS"
export const GET_TERM_SERVICE_FAILURE = "GET_TERM_SERVICE_FAILURE"

export const GET_FAQ_PENDING = "GET_FAQ_PENDING"
export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS"
export const GET_FAQ_FAILURE = "GET_FAQ_FAILURE"

export const FEEDBACK_PENDING = "FEEDBACK_PENDING"
export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS"
export const FEEDBACK_FAILURE = "FEEDBACK_FAILURE"

export const CHANGE_MAIL_PENDING = "CHANGE_MAIL_PENDING"
export const CHANGE_MAIL_SUCCESS = "CHANGE_MAIL_SUCCESS"
export const CHANGE_MAIL_FAILURE = "CHANGE_MAIL_FAILURE"

export const CHANGE_PASSWORD_PENDING = "CHANGE_PASSWORD_PENDING"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE"

export const FORGOT_PASSWORD_PENDING = "FORGOT_PASSWORD_PENDING"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"

export const CHANGE_PLAN_PENDING = "CHANGE_PLAN_PENDING"
export const CHANGE_PLAN_SUCCESS = "CHANGE_PLAN_SUCCESS"
export const CHANGE_PLAN_FAILURE = "CHANGE_PLAN_FAILURE"

export const GET_TAG_PENDING = "GET_TAG_PENDING"
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS"
export const GET_TAG_FAILURE = "GET_TAG_FAILURE"

export const CHECK_COUPON_PENDING = "CHECK_COUPON_PENDING"
export const CHECK_COUPON_SUCCESS = "CHECK_COUPON_SUCCESS"
export const CHECK_COUPON_FAILURE = "CHECK_COUPON_FAILURE"

export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const CANCEL_SUBSCRIPTION_PENDING = "CANCEL_SUBSCRIPTION_PENDING"
export const CANCEL_SUBSCRIPTION_SUCCESS = "CANCEL_SUBSCRIPTION_SUCCESS"
export const CANCEL_SUBSCRIPTION_FAILURE = "CANCEL_SUBSCRIPTION_FAILURE"

export const GET_EPISODES_PENDING = "GET_EPISODES_PENDING"
export const GET_EPISODES_SUCCESS = "GET_EPISODES_SUCCESS"
export const GET_EPISODES_FAILURE = "GET_EPISODES_FAILURE"
